In [9]:
import wbdata
import pandas as pd
import datetime

#wbdata.get_indicator(source=59)

indicators = {"NW.NFA.TO":"Net foreign assets"}
dates = (datetime.datetime(1995, 1, 1), datetime.datetime(2017, 1, 1))

df  = wbdata.get_dataframe(indicators, data_date=dates)

df

                                                    Net foreign assets
country                                       date
East Asia & Pacific                           2014        3.827741e+12
                                              2010        3.381944e+12
                                              2005        1.428162e+12
                                              2000        1.943177e+11
                                              1995       -5.061383e+11
East Asia & Pacific (low and middle income)   2014        7.843531e+11
                                              2010        1.298463e+12
                                              2005        2.389224e+11
                                              2000       -5.404881e+11
                                              1995       -7.132492e+11
Europe & Central Asia                         2014       -1.357702e+12
                                              2010       -2.205314e+12
                                              2005       -1.589812e+12
                                              2000       -1.136039e+12
                                              1995       -5.332690e+11
Europe & Central Asia (low and middle income) 2014       -7.471616e+11
                                              2010       -6.264547e+11
                                              2005       -3.988141e+11
                                              2000       -3.482367e+11
                                              1995       -1.762446e+11
High income: non-OECD                         2014        4.026035e+12
                                              2010        2.531026e+12
                                              2005        1.947992e+12
                                              2000        1.752735e+12
                                              1995        9.089257e+11
High income: OECD                             2014       -5.719109e+12
                                              2010       -3.339979e+12
                                              2005       -2.940127e+12
                                              2000       -2.803646e+12
                                              1995       -1.228725e+12
...                                                                ...
Venezuela, RB                                 2014        1.511896e+11
                                              2010        5.998274e+10
                                              2005        3.890824e+10
                                              2000       -1.160971e+10
                                              1995       -1.410330e+10
Vietnam                                       2014       -1.164662e+11
                                              2010       -1.060850e+11
                                              2005       -4.988478e+10
                                              2000       -4.457382e+10
                                              1995       -4.003981e+10
West Bank and Gaza                            2014        0.000000e+00
                                              2010        0.000000e+00
                                              2005        0.000000e+00
                                              2000        0.000000e+00
                                              1995        0.000000e+00
Yemen, Rep.                                   2014       -5.617542e+09
                                              2010        2.103437e+08
                                              2005        5.546261e+09
                                              2000       -2.205721e+09
                                              1995       -5.645927e+10
Zambia                                        2014       -4.279108e+08
                                              2010       -2.330191e+09
                                              2005       -1.641813e+10
                                              2000       -2.665151e+10
                                              1995       -2.214132e+10
Zimbabwe                                      2014       -1.542436e+10
                                              2010       -7.788496e+09
                                              2005       -9.411784e+09
                                              2000       -1.122865e+10
                                              1995       -8.113721e+09

[790 rows x 1 columns]